const express=require('express')
const app=express()
const router=express.Router()
const adminController=require('../Controllers/adminController')
const adminAuth=require('../middleWares/adminAuth')

router.post('/admin/login',adminController.postAdminLoginPage)
router.post('/admin/addlocation',adminController.locationAddPost)
router.get('/admin/location',adminController.locationGetPage)
router.delete('/admin/deleteLocation/:id',adminAuth,adminController.adminDeleteLocation)
router.patch('/admin/editLocation/:id',adminAuth,adminController.adminEditLocation)
router.get('/admin/vendors',adminController.vendorsListGetPage)
router.patch('/admin/changeStatus/:id',adminAuth,adminController.adminChangeStatusOfVendor)
router.get('/admin/users',adminController.userListGetPage)
router.patch('/admin/blockUser/:id',adminAuth,adminController.adminBlockUser)
router.post('/admin/addProperty',adminAuth,adminController.adminAddPropertyType)
router.get('/admin/property',adminController.propertyListGetPage)
router.patch('/admin/editProperty/:id',adminAuth,adminController.adminEditPropertyName)
router.delete('/admin/deleteProperty/:id',adminAuth,adminController.adminDeletePorpertyType)
module.exports=router;